from coffea import hist

var_properties = {'jet_pt': {'var_label': r'Jet $p_T$',
                             },
                  'jet_oppbtag': {'var_label': r'AK4 Jet max b-tag opp hem.',
                                  },
                  'jet_msd':{'var_label': r'Jet m$_{SD}$',
                             },
                  'fjet_pt': {'var_label': r'AK8 Jet $p_T$',
                             },
                  'fjet_msd': {'var_label': r'AK8 Jet m$_{SD}$',
                             },
                  'fjet_lsf3': {'var_label': r'AK8 Jet LSF$_{3}$',
                               },
                  'muon_pt': {'var_label': r'Muon $p_T$',
                              },
                  'muon_miso': {'var_label': r'Muon mini ISO',
                                },
                  'muon_sip': {'var_label': r'Muon SIP',
                               },
                  'electron_pt': {'var_label': r'Electron $p_T$',
                              },
                  'electron_miso': {'var_label': r'Electron mini ISO',
                                },
                  'electron_sip': {'var_label': r'Electron SIP',
                               },
                  'met_pt':{'var_label': r'MET $p_T$',
                            },
                  'met_eta':{'var_label': r'MET eta',
                             },
                  'met_phi':{'var_label': r'MET phi',
                             },
                  'jet_lsf3':{'var_label': r'Jet LSF$_{3}$',
                              },
                  'fjet_mmass':{'var_label': r'Jet - Lep mass',
                               },
                  'fjet_hmass':{'var_label': r'Jet + MET mass',
                               },
                  'flsjet_pt':{'var_label': r'Jet - Lep p$_T$',
                               },
                  'flsjet_msd':{'var_label':r'Jet - Lep m$_{SD}$',
                                },
                  'fjet_lepdR':{'var_label':r'Jet dR Lep',
                                 },
                  'fljet_lepdR':{'var_label':r'Leading Jet dR Lep',
                                 },
                  'fjet_muondR':{'var_label':r'Jet dR Lep',
                                 },
                  'jet_awaybtag':{'var_label': r'AK4 Jet b-tag max b-tag away 0.8',
                                  },
                  'genweight':{'var_label':'Gen weight',
                               },
                  'puweight':{'var_label':'Pu weight',
                              },
                  'nmuons':{'var_label':'N muons',
                            },
                  'nelectrons':{'var_label':'N electrons',
                            },
                  'muon_dz':  {'var_label': r'Muon dz',
                               },
                  'muon_dxy':  {'var_label': r'Muon dxy',
                               },
                  }

process_latex = {'tt': r'$t\bar{t}$',
                 'st': 'Single-t',
                 'zqq': 'Z(qq)',
                 'wqq': 'W(qq)',
                 'qcd': 'Multijet',
                 'wlnu': r'W($\ell\nu$)',
                 'dyll': r'Z($\ell\ell$)',
                 'vv': 'Diboson',
                 'h125': 'ggH(125)',
                 'hwwlnu': r'ggHWW$_{(qq\ell\nu)}$',
                 'hww_private': r'ggHWW priv.',
                 'data_obs_jetht': r'Data',
                 'Stat. Unc.': 'Stat. Unc.',
                 }

import re
bkgdata = re.compile("(?!hwwlnu)(?!hww_private)")
sig = re.compile("(?!qcd)(?!tt)(?!st)(?!zqq)(?!wlnu)(?!vv)(?!dyll)(?!wqq)(?!data_obs_jetht)")
privsig = re.compile("(?!qcd)(?!tt)(?!st)(?!zqq)(?!wlnu)(?!vv)(?!dyll)(?!wqq)(?!data_obs_jetht)(?!hwwlnu)")
offsig = re.compile("(?!qcd)(?!tt)(?!st)(?!zqq)(?!wlnu)(?!vv)(?!dyll)(?!wqq)(?!data_obs_jetht)(?!hww_private)")
bkg = re.compile("(?!data_obs_jetht)(?!hwwlnu)(?!hww_private)")
nodata = re.compile("(?!data_obs_jetht)")
onlyqcd = re.compile("(?!tt)(?!st)(?!zqq)(?!wlnu)(?!vv)(?!dyll)(?!wqq)(?!data_obs_jetht)(?!hwwlnu)(?!hww_private)")
